name: ChromaticVisuals
favicon: null
layout_spectrum: 0.25973285897634923
typography_spectrum: 0.18539
title: Charlie Round-Turner - Visual Creator
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.12203585426323116
  lightness: 0.7724004951305687
  saturation: 0.75
  rhythmicContrast: 0.5056669702753425
purpose: []
