name: ChromaticVisuals
favicon: null
layout_spectrum: 0.25973285897634923
typography_spectrum: 0.18539
title: Charlie Round-Turner - Visual Creator
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#090502'
    - '#676a7b'
    - '#d08800'
    - '#b6acad'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.5056669702753425
purpose: []
